import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
    <div className={styles.container}>
      <Head>
        <title>hunting coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.mainnav}>
        <ul>
          <li>Home</li>
          <li>About</li>
          <li>Blog</li>
          <li>Contacts</li>
        </ul>
      </nav>
      <main className={styles.main}>
        <div>
        <h1 className={styles.title}>Hunting Coder</h1>
        <p className={styles.description}>
          A blog for hunting coders by a hunting coder.
        </p>
        </div>
        <div className="blogs">
          <h2>Popular Blogs</h2>
          <div className="blogItem">
            <h3>How to learn javascript in 2022?</h3>
            <p>JavaScript is the language use to design for web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn javascript in 2022?</h3>
            <p>JavaScript is the language use to design for web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn javascript in 2022?</h3>
            <p>JavaScript is the language use to design for web</p>
          </div>
        </div>
      </main>
      </div>
    </>
  )
}
